name: Mirror Submodule

on:
  push:
    paths:
      - 'cours-de-math/**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run mirror script
        run: bash mirror_submodule.sh
